dist: easy_check
language: python
python:
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirement.rst
#  - pip install python-gnutls
  - python setup.py install
#virtualenv:
#  system_site_packages: true